// Rest-pose skeleton. Everything downstream (SDF anatomy, clothing, skin weights)
// reads positions from here, so proportions are changed in exactly one place.
// Space: metres, Y up, character faces +Z. Feet on y = 0.
import * as THREE from 'three';

const L = 1, R = -1;

// name -> { parent, pos }.  `.L`/`.R` pairs are generated by mirror().
const SPEC = [
  ['root', null, [0, 0, 0]],
  ['hips', 'root', [0, 0.965, 0]],
  ['spine', 'hips', [0, 1.088, 0.01]],
  ['chest', 'spine', [0, 1.225, 0.005]],
  ['upperChest', 'chest', [0, 1.368, 0]],
  ['neckBase', 'upperChest', [0, 1.455, -0.01]],
  ['neck', 'neckBase', [0, 1.516, 0.002]],
  ['head', 'neck', [0, 1.578, 0.018]],
  ['headTop', 'head', [0, 1.762, 0.01]],
  ['jaw', 'head', [0, 1.645, 0.006]],   // hinge, at the back of the lower jaw
  ['jawTip', 'jaw', [0, 1.6, 0.222]],

  ['tail1', 'hips', [0, 0.958, -0.09]],
  ['tail2', 'tail1', [0, 0.862, -0.226]],
  ['tail3', 'tail2', [0, 0.716, -0.34]],
  ['tail4', 'tail3', [0, 0.556, -0.406]],
  ['tail5', 'tail4', [0, 0.404, -0.418]],
  ['tail6', 'tail5', [0, 0.272, -0.378]],
];

const MIRROR = [
  ['clavicle', 'upperChest', [0.05, 1.406, 0.015]],
  ['shoulder', 'clavicle', [0.192, 1.409, 0]],
  ['elbow', 'shoulder', [0.211, 1.145, -0.014]],
  ['wrist', 'elbow', [0.228, 0.892, 0.012]],
  ['hand', 'wrist', [0.228, 0.828, 0.008]],

  ['thumb1', 'hand', [0.222, 0.828, 0.04]],
  ['thumb2', 'thumb1', [0.214, 0.803, 0.066]],
  ['thumb3', 'thumb2', [0.21, 0.788, 0.084]],
  ['index1', 'hand', [0.232, 0.792, 0.038]],
  ['index2', 'index1', [0.235, 0.752, 0.05]],
  ['index3', 'index2', [0.235, 0.719, 0.062]],
  ['middle1', 'hand', [0.233, 0.79, 0.011]],
  ['middle2', 'middle1', [0.236, 0.746, 0.023]],
  ['middle3', 'middle2', [0.236, 0.71, 0.036]],
  ['ring1', 'hand', [0.231, 0.79, -0.015]],
  ['ring2', 'ring1', [0.234, 0.75, -0.004]],
  ['ring3', 'ring2', [0.234, 0.717, 0.007]],
  ['pinky1', 'hand', [0.227, 0.788, -0.04]],
  ['pinky2', 'pinky1', [0.229, 0.756, -0.031]],
  ['pinky3', 'pinky2', [0.229, 0.729, -0.022]],

  ['hip', 'hips', [0.088, 0.945, 0]],
  ['knee', 'hip', [0.098, 0.525, 0.015]],
  ['ankle', 'knee', [0.1, 0.1, -0.015]],
  ['toe', 'ankle', [0.1, 0.03, 0.105]],
];

function buildSpec() {
  const out = SPEC.map(([n, p, pos]) => ({ name: n, parent: p, pos }));
  for (const side of [L, R]) {
    const sfx = side === L ? '.L' : '.R';
    for (const [n, p, pos] of MIRROR) {
      const parent = MIRROR.some((m) => m[0] === p) ? p + sfx : p;
      out.push({ name: n + sfx, parent, pos: [pos[0] * side, pos[1], pos[2]] });
    }
  }
  return out;
}

export function createSkeleton() {
  const spec = buildSpec();
  const bones = [];
  const byName = new Map();
  const restPos = new Map();

  for (const s of spec) {
    const bone = new THREE.Bone();
    bone.name = s.name;
    byName.set(s.name, bone);
    restPos.set(s.name, s.pos);
    bones.push(bone);
  }
  for (const s of spec) {
    const bone = byName.get(s.name);
    if (s.parent) {
      const parent = byName.get(s.parent);
      parent.add(bone);
      const pp = restPos.get(s.parent);
      bone.position.set(s.pos[0] - pp[0], s.pos[1] - pp[1], s.pos[2] - pp[2]);
    } else {
      bone.position.set(...s.pos);
    }
  }

  const index = new Map();
  bones.forEach((b, i) => index.set(b.name, i));
  // Skeleton's constructor snapshots bone.matrixWorld to build the bind inverses,
  // so the rest pose has to be resolved *before* it is created — otherwise every
  // vertex ends up with its rest transform applied twice.
  byName.get('root').updateMatrixWorld(true);
  const skeleton = new THREE.Skeleton(bones);

  return {
    skeleton,
    bones,
    root: byName.get('root'),
    byName,
    index,
    restPos,
    /** children of a bone, by name */
    childrenOf(name) {
      return spec.filter((s) => s.parent === name).map((s) => s.name);
    },
    spec,
  };
}

// Bones whose auto-generated span sits in the wrong flesh get hand-authored spans
// instead. Without these the upper muzzle binds to the jaw and opens with it.
const EXTRA_SEGMENTS = [
  { bone: 'head', a: [0, 1.668, 0.070], b: [0, 1.652, 0.212] },   // upper muzzle
  { bone: 'head', a: [-0.062, 1.686, 0.010], b: [0.062, 1.686, 0.010] }, // temples
  { bone: 'head', a: [0, 1.590, 0.005], b: [0, 1.756, 0.005] },   // braincase
  { bone: 'jaw', a: [0, 1.606, 0.100], b: [0, 1.601, 0.194] },    // lower jaw only
];
const SUPPRESS_AUTO = new Set(['jaw', 'jawTip', 'headTop']);

/**
 * Skinning segments. Each bone owns the span from itself to its first child
 * (leaves get a short stub along the parent direction).
 * `tweaks` lets specific bones widen/narrow their pull.
 */
export function buildSegments(rig, tweaks = {}) {
  const segs = [];
  for (const s of rig.spec) {
    if (SUPPRESS_AUTO.has(s.name)) continue;
    const kids = rig.childrenOf(s.name);
    const a = rig.restPos.get(s.name);
    let b;
    if (kids.length) {
      b = rig.restPos.get(kids[0]);
    } else {
      const pp = s.parent ? rig.restPos.get(s.parent) : [a[0], a[1] - 1, a[2]];
      b = [a[0] + (a[0] - pp[0]) * 0.4, a[1] + (a[1] - pp[1]) * 0.4, a[2] + (a[2] - pp[2]) * 0.4];
    }
    const t = tweaks[s.name] || {};
    segs.push({
      name: s.name,
      boneIndex: rig.index.get(s.name),
      a, b,
      bias: t.bias !== undefined ? t.bias : 1,
      reach: t.reach,
    });
  }
  for (const e of EXTRA_SEGMENTS) {
    const t = tweaks[e.bone] || {};
    segs.push({
      name: e.bone + ':extra',
      boneIndex: rig.index.get(e.bone),
      a: e.a, b: e.b,
      bias: e.bias !== undefined ? e.bias : (t.bias !== undefined ? t.bias : 1),
      reach: e.reach,
    });
  }
  return segs;
}
